### ISSUE TITLE
rebuild_on_webhook example?

### ISSUE THREAD

**Issue by joshRpowell** [contentful/contentful_middleman#137]
@dlitvakb could you elaborate on this feature?  perhaps with an example?

**Comment by dlitvakb** [comment]
Hey @joshRpowell,

This is a development mode option only,

What is does is that when `rebuild_on_webhook` is enabled, when running `middleman server` and having either a port open in your machine so you can configure an incoming webhook or use a tool like `ngrok` to forward the requests to your machine. This will receive Contentful Webhooks and call `middleman contentful --rebuild` in order to test your build pipeline.

You can add some other configuration options like the timeout and the actual controller that will run in the server, the default will run the said command, but you can change it to be anything else or a subclass of this one.

Does this explain what it does better?

Cheers

**Comment by joshRpowell** [comment]
Yes thank you!
