### ISSUE TITLE
Imported data missing entries

### ISSUE THREAD

**Issue by petrgazarov** [contentful/contentful_middleman#141]
hi there,

since recently `middleman contentful` started showing strange behavior. The problem we have now is that some data are missing in data/ folder. These data are published, but do not seem to be imported by middleman contentful. Moreover, some data are often omitted when using this command without any apparent pattern or reason. I tried using `contentful-cli` tool to check and got all the data from the api without omission.

This seems to happen without pattern. A single update to an unrelated entry using Contentful UI has triggered omission of several other previously existent entries. Contentful UI shows these entries as published.

My config looks like this:
```
activate :contentful do |f|
  f.space         = { home: '[reducted]' }
  f.access_token  = '[reducted]'
  f.content_types = {
    why_choose_us_section: 'whyChooseUsSection',
    footer: 'footer',
    hero: 'hero',
    leadership_team: 'leadershipTeam',
    more_about_us: 'moreAboutUs',
    offices_section: 'officesSection'
  }
end
```

This happens both on local machine and remote server (I'm using Netlify)

versions:
contentful (2.2.2)
contentful_middleman (4.0.0)

**Comment by dlitvakb** [comment]
Hey @petrgazarov,

This issue is most likely occurring because you exceeded the default `100` entries that are fetched without either enabling fetch to all entries or specifying a higher limit.

This is easily solvable by adding `f.all_entries = true` to your `activate :contentful` block. It will make sure that it will fetch all the entries in your space even if they exceed the `1000` maximum limit per request, it does so by making multiple requests until it fetches all your content, then de-serialises it all together.

Hope this helps,

Cheers

**Comment by petrgazarov** [comment]
hi @dlitvakb, adding `f.all_entries = true` did the trick, thanks
