### ISSUE TITLE
Unable to import multiple content types 

### ISSUE THREAD

**Issue by BooneTeam** [contentful/contentful_middleman#150]
While doing what was suggested in [this closed ticket](https://github.com/contentful/contentful_middleman/issues/35) it seems to just overwrite the products folder and create a suggested_products folder within contentful 
```
activate :contentful do |f|
  f.space         = { contentful: ENV['CONTENTFUL_SPACE_KEY'] }
  f.access_token  = ENV['CONTENTFUL_ACCESS_TOKEN']
  f.client_options = { environment: ENV['CONTENTFUL_ENVIRONMENT'] || 'development' }
  f.content_types = { products: 'product', suggested_products: 'suggestedProduct' }
end
```

**Comment by dlitvakb** [comment]
Hey @BooneTeam,

I tried replicating the issue you mention with our example space, and haven't been able to replicate it.

The `Gemfile` is:
```ruby
source 'https://rubygems.org'

gem 'contentful_middleman'
gem 'middleman'
```

The `config.rb` is:
```ruby
require 'contentful_middleman'

activate :contentful do |f|
  f.space = {test: 'cfexampleapi'}
  f.access_token = 'b4c0n73n7fu1'
  f.content_types = {cats: 'cat', humans: 'human'}
end
```

The generated folder tree is:
```
▾ data/
  ▾ test/
    ▾ cats/
        garfield.yaml
        happycat.yaml
        nyancat.yaml
    ▾ humans/
        finn.yaml
  config.rb
  Gemfile
  Gemfile.lock
```

Versions installed:
```
middleman 4.2.1
contentful_middleman 4.2.0
```

Import command output:
```
$ middleman contentful
      create  data/test/cats/garfield.yaml
      create  data/test/cats/nyancat.yaml
      create  data/test/humans/finn.yaml
      create  data/test/cats/happycat.yaml
      create  data/test/cats/garfield.yaml
      create  data/test/cats/nyancat.yaml
      create  data/test/humans/finn.yaml
      create  data/test/cats/happycat.yaml
```

If you have more than 100 entries of either of the types, and the response of the request to contentful may only contain one of the types, then I recommend adding to your `activate` block the following:

```ruby
activate :contentful do |f|
  # ... all the config you already specified ...
  f.all_entries = true
end
```

This will ensure that all entries on the space are fetched, and then serialized according to the content type mappings you provided.

Cheers

**Comment by BooneTeam** [comment]
Thanks @dlitvakb!

This line solved it. 
```
f.all_entries = true
```
When talking of 'entries' is this counting nested entries as well? I only have 18 suggestedProducts and 2 Products but for some reason it wasn't fetching all of them until adding that line.

**Comment by dlitvakb** [comment]
Hey @BooneTeam,

The way this library works, is that by default, unless specified explicitly, it will request `/entries` without sending any additional parameters, this means that the library will fetch the first 100 entries the API replies with, with no specific order. Then inside that response will look for the content types you requested. This means that if you have over 100 entries, the default behaviour, will most likely miss some of your content.

That's why you can customize the CDA query that's sent, and also use `all_entries`, to request as many times as necessary the API, in order to fetch all of your content and not be omitting anything.

Hope this explains it better,

Cheers
