### ISSUE TITLE
Need to specify order when pulling in more than 1000 entries from Contentful 

### ISSUE THREAD

**Issue by gracelauren** [contentful/contentful_middleman#60]
We found that if an order is not specified in the query for pulling down contentful data that some data is randomly skipped and you don't receive the full data set. This can be solved either in the configuration block in `config.rb` where you add to the cda_query: `order: 'sys.createdAt'` OR in the `instance.rb` file of the all_entries method where you could add: `query[:order] = 'sys.createdAt'` after the skip query.

**Comment by dlitvakb** [comment]
Hey @gracelauren,

Thanks for the input, regarding adding ordering built-in into the ContentfulMiddleman::Instance, we've thought of that, but dropped it away because if we added ordering inside there, it would override any ordering you may want to add on the configuration block.

Would you suggest, that adding a note on the README.md regarding ordering would be helpful?

Hope to hearing from you soon

**Comment by gracelauren** [comment]
Hey @dlitvakb  I think a note in the README.md around the where you are talking about the ability to grab all entries would be good just in case it isn't apparent that without specifying any sort of order, you run the chance of skipping some of the data when you pull down. Thanks for getting back so quickly!

**Comment by dlitvakb** [comment]
Hey @gracelauren,

No problem!

Will add a note!

**Comment by gracelauren** [comment]
:+1:
