### ISSUE TITLE
TypeError when the ContentType contains integer id

### ISSUE THREAD

**Issue by yanickouellet** [contentful/contentful_middleman#77]
In Contentful, if I have a content type with an integer field named `id`, it seems cause a TypeError here https://github.com/contentful/contentful_middleman/blob/master/lib/contentful_middleman/import_task.rb#L38 because entry.id is an Integer.

Also, if I use a string for the field name instead of an int (and the id is still numeric, ex: 1001), the import works the first time, but after, it does another type error:
`middleman-core-3.3.7/lib/middleman-core/core_extensions/data.rb:110:in `[]': no implicit conversion of String into Integer (TypeError)`. 

Am-I the only one with this problem?

**Comment by dlitvakb** [comment]
Hey @yanickouellet,

Sadly this is a limitation of the `contentful.rb` gem in which `contentful_middleman` relies.

Fields with `id` as name shadow `sys.id` which can cause some amount of problems.

I'm not certain of the extent of this, and will take a bit to test.

The temporary solution is to rename that field to `internal_id` or something of sorts, so that it doesn't conflict with the libraries behaviour.

Though this will be addressed in a permanent way, some time during next week.

Hope this helps

**Comment by dlitvakb** [comment]
Hey @yanickouellet,

Found a nice easy to implement solution that can work permanently.

PR Created and referenced above.

Sorry if this bug caused you any significant troubles,

Cheers

**Comment by yanickouellet** [comment]
Hey @dlitvakb , 

It is not a big issue for me, I will use other field name until the PR is merged, but thanks for the quick fix, it is really appreciated!
