### ISSUE TITLE
Feature: Include created_at and updated_at in data files.

### ISSUE THREAD

**Issue by chuise** [contentful/contentful_middleman#93]
It would be nice to have the created_at and updated_at dates available for each record that gets created. Most of our records need to be sorted in some way, usually by date, and it's kind of a pain to have to keep creating additional fields on each content type for the publish date.

**Comment by dlitvakb** [comment]
Hey @chuise,

Have you read about Custom Mappers?

You can include those fields by creating one like follows:

```ruby
class DatesMapper < ContentfulMiddleman::Mapper::Base
  def map(context, entry)
    super
    context.created_at = entry.sys[:createdAt]
    context.updated_at = entry.sys[:updatedAt]
  end
end
```

Then when activating the Contentful extension, add it in your content type declaration as follows:

```ruby
f.content_types = {my_content_type: {mapper: DatesMapper, id: 'my_content_type_id'}}
```

You can reuse this same mapper for every content type, as it is already covering what the default one does and `sys` attributes are generic for all entries.

Hope that helps

**Comment by chuise** [comment]
Hey @dlitvakb never thought of using custom mappers for this. Going to try that right now!

Thanks!

**Comment by dlitvakb** [comment]
No problem!

Did it work?

Cheers

**Comment by j0b0sapi3n** [comment]
How does one do this but for every nested piece of Content as well in the YAML file? Assuming your example, let's say the YAML file generated based on `my_content_type` has a few nested levels with references to other types of Content and we also want to include `updatedAt` for those as well, not just `my_content_type`?

**Comment by dlitvakb** [comment]
Hey @j0b0sapi3n,

After giving it some thought, I will add some of the `sys` properties to entry serialization.

I'll add an `__meta` section to each entry (and all it's nested entries) that includes `updatedAt` and `createdAt`. I'll look into adding more properties.

The naming of the section as `__meta` is in order to avoid any kind of collision with any existing mapper. This might change if a 2.0 version is released, and be changed back to `sys`. But right now avoiding conflicts if my number 1 priority.

Cheers

**Comment by j0b0sapi3n** [comment]
@dlitvakb Awesome, thank you!

**Comment by dlitvakb** [comment]
This is currently being worked on and a release will be done early tomorrow.

Cheers
